<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! class_exists( 'Blockspare_Testimonials_Template_Block' ) ) {

	class Blockspare_Testimonials_Template_Block extends Blockspare_Import_Block_Base{
		public static function get_instance() {

			static $instance = null;
			if ( null === $instance ) {
				$instance = new self();
			}
			return $instance;

		}
        public function add_block_template_library( $blocks_lists ){

            $block_library_list = array(
					array(
						'type'     => 'block',
						'key'      => 'bs_testimonial_1',
						'name'     => esc_html__( 'Testimonial', 'blockspare' ),
						'content'  => '<!-- wp:blockspare/blockspare-testimonial {"uniqueClass":"blockspare-86447d0c-15ed-4"} -->
						<div class="wp-block-blockspare-blockspare-testimonial alignwide blockspare-86447d0c-15ed-4 alignwide"><div class="blockspare-main-testimonial-wrapper blockspare-item blockspare-testimonial-columns-3 blockspare-testimonial-gap-1 bs-layout-1"><style>.blockspare-86447d0c-15ed-4 .blockspare-main-testimonial-wrapper{margin-top:30px;margin-bottom:30px}</style><!-- wp:blockspare/testimonial-item {"uniqueClass":"blockspare-78883f8c-0c24-4","headerTitle":"CEO","headerSubTitle":"","padding":20} -->
						<div class="wp-block-blockspare-testimonial-item blockspare-78883f8c-0c24-4 blockspare-testimonials textalignment-center"><style>.blockspare-78883f8c-0c24-4 .blockspare-block-testimonial-wrap{background-color:#fff;border-width:1px;border-style:solid;border-color:#ececec;border-radius:null;padding:20px}.blockspare-78883f8c-0c24-4 .blockspare-section-head-wrap{background-color:transparent;text-align:center;padding-top:5px;padding-bottom:5px;margin-top:5px;margin-bottom:5px}.blockspare-78883f8c-0c24-4 .blockspare-section-head-wrap .blockspare-title{color:#404040;font-size:32px;font-family:Default;font-weight:undefined!important;padding-top:5px;padding-bottom:5px}.blockspare-78883f8c-0c24-4 .blockspare-section-head-wrap .blockspare-subtitle{color:#6d6d6d;font-size:18px;font-family:Default;font-weight:Default!important;padding-top:5px;padding-bottom:5px}.blockspare-78883f8c-0c24-4 .blockspare-description{color:#6d6d6d;font-size:16px;font-family:Default;text-align:center;font-weight:undefined!important}.blockspare-78883f8c-0c24-4 .blockspare-title-dash{color:#8b249c}@media screen and (max-width:1025px){.blockspare-78883f8c-0c24-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-78883f8c-0c24-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-78883f8c-0c24-4 .blockspare-description{font-size:undefinedpx}}@media screen and (max-width:768px){.blockspare-78883f8c-0c24-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-78883f8c-0c24-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-78883f8c-0c24-4 .blockspare-description{font-size:undefinedpx}}</style><div class="blockspare-block-testimonial-wrap"><div class="blockspare-author-wrap"><div class="blockspare-img-wrapper"><!-- wp:image {"align":"center","id":393,"width":165,"height":165,"sizeSlug":"large","linkDestination":"none","className":"is-style-rounded"} -->
						<div class="wp-block-image is-style-rounded"><figure class="aligncenter size-large is-resized"><img src="https://www.blockspare.com/free/wp-content/uploads/sites/2/2021/02/pexels-august-de-richelieu-4427506-edited-1.jpg" alt="" class="wp-image-393" width="165" height="165"/></figure></div>
						<!-- /wp:image --></div></div><div class="blockspare-author-designation"><div class="blockspare-section-header-wrapper blockspare-blocks aligncenter"><div class="blockspare-section-head-wrap blockspare-style1 blockspare-center"><div class="blockspare-title-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><h2 class="blockspare-title">CEO</h2><span class="blockspare-title-dash blockspare-lower-dash"></span></div><div class="blockspare-subtitle-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><span class="blockspare-title-dash blockspare-lower-dash"></span></div></div></div></div><div class="blockspare-testimonial-content"><p class="blockspare-description">Donec odit magni, nesciunt pariatur! Nec, purus voluptate ridiculus odit nobis euismod, ac laudantium facere perferendis! </p></div></div></div>
						<!-- /wp:blockspare/testimonial-item -->
						
						<!-- wp:blockspare/testimonial-item {"uniqueClass":"blockspare-bc66be52-6f83-4","headerTitle":"Co-Founder","headerSubTitle":"","padding":20} -->
						<div class="wp-block-blockspare-testimonial-item blockspare-bc66be52-6f83-4 blockspare-testimonials textalignment-center"><style>.blockspare-bc66be52-6f83-4 .blockspare-block-testimonial-wrap{background-color:#fff;border-width:1px;border-style:solid;border-color:#ececec;border-radius:null;padding:20px}.blockspare-bc66be52-6f83-4 .blockspare-section-head-wrap{background-color:transparent;text-align:center;padding-top:5px;padding-bottom:5px;margin-top:5px;margin-bottom:5px}.blockspare-bc66be52-6f83-4 .blockspare-section-head-wrap .blockspare-title{color:#404040;font-size:32px;font-family:Default;font-weight:undefined!important;padding-top:5px;padding-bottom:5px}.blockspare-bc66be52-6f83-4 .blockspare-section-head-wrap .blockspare-subtitle{color:#6d6d6d;font-size:18px;font-family:Default;font-weight:Default!important;padding-top:5px;padding-bottom:5px}.blockspare-bc66be52-6f83-4 .blockspare-description{color:#6d6d6d;font-size:16px;font-family:Default;text-align:center;font-weight:undefined!important}.blockspare-bc66be52-6f83-4 .blockspare-title-dash{color:#8b249c}@media screen and (max-width:1025px){.blockspare-bc66be52-6f83-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-bc66be52-6f83-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-bc66be52-6f83-4 .blockspare-description{font-size:undefinedpx}}@media screen and (max-width:768px){.blockspare-bc66be52-6f83-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-bc66be52-6f83-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-bc66be52-6f83-4 .blockspare-description{font-size:undefinedpx}}</style><div class="blockspare-block-testimonial-wrap"><div class="blockspare-author-wrap"><div class="blockspare-img-wrapper"><!-- wp:image {"align":"center","id":394,"width":165,"height":165,"sizeSlug":"large","linkDestination":"none","className":"is-style-rounded"} -->
						<div class="wp-block-image is-style-rounded"><figure class="aligncenter size-large is-resized"><img src="https://www.blockspare.com/free/wp-content/uploads/sites/2/2021/02/pexels-sora-shimazaki-5668870-1-edited.jpg" alt="" class="wp-image-394" width="165" height="165"/></figure></div>
						<!-- /wp:image --></div></div><div class="blockspare-author-designation"><div class="blockspare-section-header-wrapper blockspare-blocks aligncenter"><div class="blockspare-section-head-wrap blockspare-style1 blockspare-center"><div class="blockspare-title-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><h2 class="blockspare-title">Co-Founder</h2><span class="blockspare-title-dash blockspare-lower-dash"></span></div><div class="blockspare-subtitle-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><span class="blockspare-title-dash blockspare-lower-dash"></span></div></div></div></div><div class="blockspare-testimonial-content"><p class="blockspare-description">Donec odit magni, nesciunt pariatur! Nec, purus voluptate ridiculus odit nobis euismod, ac laudantium facere perferendis! </p></div></div></div>
						<!-- /wp:blockspare/testimonial-item -->
						
						<!-- wp:blockspare/testimonial-item {"uniqueClass":"blockspare-a31a4202-b072-4","headerTitle":"Manager","headerSubTitle":"","padding":20} -->
						<div class="wp-block-blockspare-testimonial-item blockspare-a31a4202-b072-4 blockspare-testimonials textalignment-center"><style>.blockspare-a31a4202-b072-4 .blockspare-block-testimonial-wrap{background-color:#fff;border-width:1px;border-style:solid;border-color:#ececec;border-radius:null;padding:20px}.blockspare-a31a4202-b072-4 .blockspare-section-head-wrap{background-color:transparent;text-align:center;padding-top:5px;padding-bottom:5px;margin-top:5px;margin-bottom:5px}.blockspare-a31a4202-b072-4 .blockspare-section-head-wrap .blockspare-title{color:#404040;font-size:32px;font-family:Default;font-weight:undefined!important;padding-top:5px;padding-bottom:5px}.blockspare-a31a4202-b072-4 .blockspare-section-head-wrap .blockspare-subtitle{color:#6d6d6d;font-size:18px;font-family:Default;font-weight:Default!important;padding-top:5px;padding-bottom:5px}.blockspare-a31a4202-b072-4 .blockspare-description{color:#6d6d6d;font-size:16px;font-family:Default;text-align:center;font-weight:undefined!important}.blockspare-a31a4202-b072-4 .blockspare-title-dash{color:#8b249c}@media screen and (max-width:1025px){.blockspare-a31a4202-b072-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-a31a4202-b072-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-a31a4202-b072-4 .blockspare-description{font-size:undefinedpx}}@media screen and (max-width:768px){.blockspare-a31a4202-b072-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-a31a4202-b072-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-a31a4202-b072-4 .blockspare-description{font-size:undefinedpx}}</style><div class="blockspare-block-testimonial-wrap"><div class="blockspare-author-wrap"><div class="blockspare-img-wrapper"><!-- wp:image {"align":"center","id":396,"width":165,"height":165,"sizeSlug":"large","linkDestination":"none","className":"is-style-rounded"} -->
						<div class="wp-block-image is-style-rounded"><figure class="aligncenter size-large is-resized"><img src="https://www.blockspare.com/free/wp-content/uploads/sites/2/2021/02/pexels-emmy-e-2381069-edited.jpg" alt="" class="wp-image-396" width="165" height="165"/></figure></div>
						<!-- /wp:image --></div></div><div class="blockspare-author-designation"><div class="blockspare-section-header-wrapper blockspare-blocks aligncenter"><div class="blockspare-section-head-wrap blockspare-style1 blockspare-center"><div class="blockspare-title-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><h2 class="blockspare-title">Manager</h2><span class="blockspare-title-dash blockspare-lower-dash"></span></div><div class="blockspare-subtitle-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><span class="blockspare-title-dash blockspare-lower-dash"></span></div></div></div></div><div class="blockspare-testimonial-content"><p class="blockspare-description">Donec odit magni, nesciunt pariatur! Nec, purus voluptate ridiculus odit nobis euismod, ac laudantium facere perferendis! </p></div></div></div>
						<!-- /wp:blockspare/testimonial-item --></div></div>
						<!-- /wp:blockspare/blockspare-testimonial -->',
						'category' => [ esc_html__( 'testimonial', 'blockspare' ) ],
						'keywords' => [
							esc_html__( 'testimonial', 'blockspare' ),
							
						],
						'image'    => BLOCKSPARE_BLOCK_LIBRARY_URL.'testimonials/testimonial-1.png',
				),
				array(
					'type'     => 'block',
					'key'      => 'bs_testimonial_2',
					'name'     => esc_html__( 'Testimonial 2', 'blockspare' ),
					'content'  => '<!-- wp:blockspare/blockspare-testimonial {"columnsGap":2,"marginTop":0,"marginBottom":0,"uniqueClass":"blockspare-5341ea28-8ba4-4"} -->
					<div class="wp-block-blockspare-blockspare-testimonial alignwide blockspare-5341ea28-8ba4-4 alignwide"><div class="blockspare-main-testimonial-wrapper blockspare-item blockspare-testimonial-columns-3 blockspare-testimonial-gap-2 bs-layout-1"><!-- wp:blockspare/testimonial-item {"uniqueClass":"blockspare-dc3399c2-c5bb-4","headerTitle":"Coriss Ambady","titleFontSize":20,"headerSubTitle":"\u003cstrong\u003eFINANCIAL ANALYST\u003c/strong\u003e","headerTagOption":"h4","subTitleFontSize":14,"testimonialDescription":"Nunc nulla. Mauris turpis nunc, blandit et, volutpat molestie, porta ut, ligula. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Aenean massa. Etiam sit amet orci eget eros faucibus tincidunt.","padding":20,"descriptionFontSize":13,"descriptionFontWeight":"400"} -->
					<div class="wp-block-blockspare-testimonial-item blockspare-dc3399c2-c5bb-4 blockspare-testimonials textalignment-center"><style>.blockspare-dc3399c2-c5bb-4 .blockspare-block-testimonial-wrap{background-color:#fff;border-width:1px;border-style:solid;border-color:#ececec;border-radius:null;padding:20px}.blockspare-dc3399c2-c5bb-4 .blockspare-section-head-wrap{background-color:transparent;text-align:center;padding-top:5px;padding-bottom:5px;margin-top:5px;margin-bottom:5px}.blockspare-dc3399c2-c5bb-4 .blockspare-section-head-wrap .blockspare-title{color:#404040;font-size:20px;font-family:Default;font-weight:undefined!important;padding-top:5px;padding-bottom:5px}.blockspare-dc3399c2-c5bb-4 .blockspare-section-head-wrap .blockspare-subtitle{color:#6d6d6d;font-size:14px;font-family:Default;font-weight:Default!important;padding-top:5px;padding-bottom:5px}.blockspare-dc3399c2-c5bb-4 .blockspare-description{color:#6d6d6d;font-size:13px;font-family:Default;text-align:center;font-weight:400!important}.blockspare-dc3399c2-c5bb-4 .blockspare-title-dash{color:#8b249c}@media screen and (max-width:1025px){.blockspare-dc3399c2-c5bb-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-dc3399c2-c5bb-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-dc3399c2-c5bb-4 .blockspare-description{font-size:undefinedpx}}@media screen and (max-width:768px){.blockspare-dc3399c2-c5bb-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-dc3399c2-c5bb-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-dc3399c2-c5bb-4 .blockspare-description{font-size:undefinedpx}}</style><div class="blockspare-block-testimonial-wrap"><div class="blockspare-author-wrap"><div class="blockspare-img-wrapper"><!-- wp:image {"align":"center","id":71,"width":119,"height":119,"sizeSlug":"large","linkDestination":"none","className":"is-style-rounded"} -->
					<div class="wp-block-image is-style-rounded"><figure class="aligncenter size-large is-resized"><img src="https://blockspare.com/demo/default/agency/wp-content/uploads/sites/2/2021/07/photo-1570295999919-56ceb5ecca61.jpeg" alt="" class="wp-image-71" width="119" height="119"/></figure></div>
					<!-- /wp:image --></div></div><div class="blockspare-author-designation"><div class="blockspare-section-header-wrapper blockspare-blocks aligncenter"><div class="blockspare-section-head-wrap blockspare-style1 blockspare-center"><div class="blockspare-title-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><h4 class="blockspare-title">Coriss Ambady</h4><span class="blockspare-title-dash blockspare-lower-dash"></span></div><div class="blockspare-subtitle-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><p class="blockspare-subtitle"><strong>FINANCIAL ANALYST</strong></p><span class="blockspare-title-dash blockspare-lower-dash"></span></div></div></div></div><div class="blockspare-testimonial-content"><p class="blockspare-description">Nunc nulla. Mauris turpis nunc, blandit et, volutpat molestie, porta ut, ligula. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Aenean massa. Etiam sit amet orci eget eros faucibus tincidunt.</p></div></div></div>
					<!-- /wp:blockspare/testimonial-item -->
					
					<!-- wp:blockspare/testimonial-item {"uniqueClass":"blockspare-7533bd55-e7db-4","headerTitle":"Coriss Ambady","titleFontSize":20,"headerSubTitle":"\u003cstrong\u003eFINANCIAL ANALYST\u003c/strong\u003e","headerTagOption":"h4","subTitleFontSize":14,"testimonialDescription":"Nunc nulla. Mauris turpis nunc, blandit et, volutpat molestie, porta ut, ligula. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Aenean massa. Etiam sit amet orci eget eros faucibus tincidunt.","padding":20,"descriptionFontSize":13,"descriptionFontWeight":"400"} -->
					<div class="wp-block-blockspare-testimonial-item blockspare-7533bd55-e7db-4 blockspare-testimonials textalignment-center"><style>.blockspare-7533bd55-e7db-4 .blockspare-block-testimonial-wrap{background-color:#fff;border-width:1px;border-style:solid;border-color:#ececec;border-radius:null;padding:20px}.blockspare-7533bd55-e7db-4 .blockspare-section-head-wrap{background-color:transparent;text-align:center;padding-top:5px;padding-bottom:5px;margin-top:5px;margin-bottom:5px}.blockspare-7533bd55-e7db-4 .blockspare-section-head-wrap .blockspare-title{color:#404040;font-size:20px;font-family:Default;font-weight:undefined!important;padding-top:5px;padding-bottom:5px}.blockspare-7533bd55-e7db-4 .blockspare-section-head-wrap .blockspare-subtitle{color:#6d6d6d;font-size:14px;font-family:Default;font-weight:Default!important;padding-top:5px;padding-bottom:5px}.blockspare-7533bd55-e7db-4 .blockspare-description{color:#6d6d6d;font-size:13px;font-family:Default;text-align:center;font-weight:400!important}.blockspare-7533bd55-e7db-4 .blockspare-title-dash{color:#8b249c}@media screen and (max-width:1025px){.blockspare-7533bd55-e7db-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-7533bd55-e7db-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-7533bd55-e7db-4 .blockspare-description{font-size:undefinedpx}}@media screen and (max-width:768px){.blockspare-7533bd55-e7db-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-7533bd55-e7db-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-7533bd55-e7db-4 .blockspare-description{font-size:undefinedpx}}</style><div class="blockspare-block-testimonial-wrap"><div class="blockspare-author-wrap"><div class="blockspare-img-wrapper"><!-- wp:image {"align":"center","id":71,"width":118,"height":118,"sizeSlug":"large","linkDestination":"none","className":"is-style-rounded"} -->
					<div class="wp-block-image is-style-rounded"><figure class="aligncenter size-large is-resized"><img src="https://blockspare.com/demo/default/agency/wp-content/uploads/sites/2/2021/07/photo-1570295999919-56ceb5ecca61.jpeg" alt="" class="wp-image-71" width="118" height="118"/></figure></div>
					<!-- /wp:image --></div></div><div class="blockspare-author-designation"><div class="blockspare-section-header-wrapper blockspare-blocks aligncenter"><div class="blockspare-section-head-wrap blockspare-style1 blockspare-center"><div class="blockspare-title-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><h4 class="blockspare-title">Coriss Ambady</h4><span class="blockspare-title-dash blockspare-lower-dash"></span></div><div class="blockspare-subtitle-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><p class="blockspare-subtitle"><strong>FINANCIAL ANALYST</strong></p><span class="blockspare-title-dash blockspare-lower-dash"></span></div></div></div></div><div class="blockspare-testimonial-content"><p class="blockspare-description">Nunc nulla. Mauris turpis nunc, blandit et, volutpat molestie, porta ut, ligula. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Aenean massa. Etiam sit amet orci eget eros faucibus tincidunt.</p></div></div></div>
					<!-- /wp:blockspare/testimonial-item -->
					
					<!-- wp:blockspare/testimonial-item {"uniqueClass":"blockspare-3a836eeb-6411-4","headerTitle":"Coriss Ambady","titleFontSize":20,"headerSubTitle":"\u003cstrong\u003eFINANCIAL ANALYST\u003c/strong\u003e","headerTagOption":"h4","subTitleFontSize":14,"testimonialDescription":"Nunc nulla. Mauris turpis nunc, blandit et, volutpat molestie, porta ut, ligula. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Aenean massa. Etiam sit amet orci eget eros faucibus tincidunt.","padding":20,"descriptionFontSize":13,"descriptionFontWeight":"400"} -->
					<div class="wp-block-blockspare-testimonial-item blockspare-3a836eeb-6411-4 blockspare-testimonials textalignment-center"><style>.blockspare-3a836eeb-6411-4 .blockspare-block-testimonial-wrap{background-color:#fff;border-width:1px;border-style:solid;border-color:#ececec;border-radius:null;padding:20px}.blockspare-3a836eeb-6411-4 .blockspare-section-head-wrap{background-color:transparent;text-align:center;padding-top:5px;padding-bottom:5px;margin-top:5px;margin-bottom:5px}.blockspare-3a836eeb-6411-4 .blockspare-section-head-wrap .blockspare-title{color:#404040;font-size:20px;font-family:Default;font-weight:undefined!important;padding-top:5px;padding-bottom:5px}.blockspare-3a836eeb-6411-4 .blockspare-section-head-wrap .blockspare-subtitle{color:#6d6d6d;font-size:14px;font-family:Default;font-weight:Default!important;padding-top:5px;padding-bottom:5px}.blockspare-3a836eeb-6411-4 .blockspare-description{color:#6d6d6d;font-size:13px;font-family:Default;text-align:center;font-weight:400!important}.blockspare-3a836eeb-6411-4 .blockspare-title-dash{color:#8b249c}@media screen and (max-width:1025px){.blockspare-3a836eeb-6411-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-3a836eeb-6411-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-3a836eeb-6411-4 .blockspare-description{font-size:undefinedpx}}@media screen and (max-width:768px){.blockspare-3a836eeb-6411-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-3a836eeb-6411-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-3a836eeb-6411-4 .blockspare-description{font-size:undefinedpx}}</style><div class="blockspare-block-testimonial-wrap"><div class="blockspare-author-wrap"><div class="blockspare-img-wrapper"><!-- wp:image {"align":"center","id":71,"width":118,"height":118,"sizeSlug":"large","linkDestination":"none","className":"is-style-rounded"} -->
					<div class="wp-block-image is-style-rounded"><figure class="aligncenter size-large is-resized"><img src="https://blockspare.com/demo/default/agency/wp-content/uploads/sites/2/2021/07/photo-1570295999919-56ceb5ecca61.jpeg" alt="" class="wp-image-71" width="118" height="118"/></figure></div>
					<!-- /wp:image --></div></div><div class="blockspare-author-designation"><div class="blockspare-section-header-wrapper blockspare-blocks aligncenter"><div class="blockspare-section-head-wrap blockspare-style1 blockspare-center"><div class="blockspare-title-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><h4 class="blockspare-title">Coriss Ambady</h4><span class="blockspare-title-dash blockspare-lower-dash"></span></div><div class="blockspare-subtitle-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><p class="blockspare-subtitle"><strong>FINANCIAL ANALYST</strong></p><span class="blockspare-title-dash blockspare-lower-dash"></span></div></div></div></div><div class="blockspare-testimonial-content"><p class="blockspare-description">Nunc nulla. Mauris turpis nunc, blandit et, volutpat molestie, porta ut, ligula. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Aenean massa. Etiam sit amet orci eget eros faucibus tincidunt.</p></div></div></div>
					<!-- /wp:blockspare/testimonial-item --></div></div>
					<!-- /wp:blockspare/blockspare-testimonial -->',
					'category' => [ esc_html__( 'testimonial', 'blockspare' ) ],
					'keywords' => [
						esc_html__( 'testimonial', 'blockspare' ),
						
					],
					'image'    => BLOCKSPARE_BLOCK_LIBRARY_URL.'testimonials/testimonial-2.png',
				),
				array(
					'type'     => 'block',
					'key'      => 'bs_testimonial_3',
					'name'     => esc_html__( 'Testimonial 3', 'blockspare' ),
					'content'  => '<!-- wp:blockspare/blockspare-testimonial {"uniqueClass":"blockspare-457918e4-1406-4"} -->
					<div class="wp-block-blockspare-blockspare-testimonial alignwide blockspare-457918e4-1406-4 alignwide"><div class="blockspare-main-testimonial-wrapper blockspare-item blockspare-testimonial-columns-3 blockspare-testimonial-gap-1 bs-layout-1"><style>.blockspare-457918e4-1406-4 .blockspare-main-testimonial-wrapper{margin-top:30px;margin-bottom:30px}</style><!-- wp:blockspare/testimonial-item {"uniqueClass":"blockspare-27903872-3536-4","headerTitle":"\u0022Gorgeous Design\u0022","titleFontSize":20,"headerSubTitle":"Jane Doe","headertitleColor":"#ffffff","headersubtitleColor":"#ffffff","titleFontFamily":"Poppins","titleFontWeight":"400","titleFontSubset":"latin","titleLoadGoogleFonts":true,"subTitleFontFamily":"Poppins","subTitleFontWeight":"400","subTitleFontSubset":"latin","subTitleLoadGoogleFonts":true,"testimonialDescription":"Molestiae incidunt consequatur quis ipsa autem nam sit enim magni. Voluptas tempore rem. Explicabo a quaerat sint autem dolore ducimus ut consequatur neque quaerat fuga rem nihil nostrum.\u003cbr\u003e","testimonialDescriptionTextColor":"#ffffff","backGroundColor":"#ea4b50","borderWidth":0} -->
					<div class="wp-block-blockspare-testimonial-item blockspare-27903872-3536-4 blockspare-testimonials textalignment-center"><style>.blockspare-27903872-3536-4 .blockspare-block-testimonial-wrap{background-color:#ea4b50;border-width:null;border-style:null;border-color:#ececec;border-radius:null;padding:15px}.blockspare-27903872-3536-4 .blockspare-section-head-wrap{background-color:transparent;text-align:center;padding-top:5px;padding-bottom:5px;margin-top:5px;margin-bottom:5px}.blockspare-27903872-3536-4 .blockspare-section-head-wrap .blockspare-title{color:#ffffff;font-size:20px;font-family:Poppins;font-weight:400!important;padding-top:5px;padding-bottom:5px}.blockspare-27903872-3536-4 .blockspare-section-head-wrap .blockspare-subtitle{color:#ffffff;font-size:18px;font-family:Poppins;font-weight:Poppins!important;padding-top:5px;padding-bottom:5px}.blockspare-27903872-3536-4 .blockspare-description{color:#ffffff;font-size:16px;font-family:Default;text-align:center;font-weight:undefined!important}.blockspare-27903872-3536-4 .blockspare-title-dash{color:#8b249c}@media screen and (max-width:1025px){.blockspare-27903872-3536-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-27903872-3536-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-27903872-3536-4 .blockspare-description{font-size:undefinedpx}}@media screen and (max-width:768px){.blockspare-27903872-3536-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-27903872-3536-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-27903872-3536-4 .blockspare-description{font-size:undefinedpx}}</style><div class="blockspare-block-testimonial-wrap"><div class="blockspare-author-wrap"><div class="blockspare-img-wrapper"><!-- wp:image {"align":"center","id":86,"width":160,"height":160,"sizeSlug":"full","linkDestination":"none","className":"is-style-rounded"} -->
					<div class="wp-block-image is-style-rounded"><figure class="aligncenter size-full is-resized"><img src="https://blockspare.com/demo/default/app/wp-content/uploads/sites/5/2021/09/pexels-mateus-souza-3586798-edited.jpg" alt="" class="wp-image-86" width="160" height="160"/></figure></div>
					<!-- /wp:image --></div></div><div class="blockspare-author-designation"><div class="blockspare-section-header-wrapper blockspare-blocks aligncenter"><div class="blockspare-section-head-wrap blockspare-style1 blockspare-center"><div class="blockspare-title-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><h2 class="blockspare-title">"Gorgeous Design"</h2><span class="blockspare-title-dash blockspare-lower-dash"></span></div><div class="blockspare-subtitle-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><p class="blockspare-subtitle">Jane Doe</p><span class="blockspare-title-dash blockspare-lower-dash"></span></div></div></div></div><div class="blockspare-testimonial-content"><p class="blockspare-description">Molestiae incidunt consequatur quis ipsa autem nam sit enim magni. Voluptas tempore rem. Explicabo a quaerat sint autem dolore ducimus ut consequatur neque quaerat fuga rem nihil nostrum.<br></p></div></div></div>
					<!-- /wp:blockspare/testimonial-item -->
					
					<!-- wp:blockspare/testimonial-item {"uniqueClass":"blockspare-62f1cbbf-5319-4","headerTitle":"\u0022Gorgeous Design\u0022","titleFontSize":20,"headerSubTitle":"John Doe","headertitleColor":"#ffffff","headersubtitleColor":"#ffffff","titleFontFamily":"Poppins","titleFontWeight":"400","titleFontSubset":"latin","titleLoadGoogleFonts":true,"subTitleFontFamily":"Poppins","subTitleFontWeight":"400","subTitleFontSubset":"latin","subTitleLoadGoogleFonts":true,"testimonialDescription":"Molestiae incidunt consequatur quis ipsa autem nam sit enim magni. Voluptas tempore rem. Explicabo a quaerat sint autem dolore ducimus ut consequatur neque quaerat fuga rem nihil nostrum.\u003cbr\u003e","testimonialDescriptionTextColor":"#ffffff","backGroundColor":"#ea4b50","borderWidth":0} -->
					<div class="wp-block-blockspare-testimonial-item blockspare-62f1cbbf-5319-4 blockspare-testimonials textalignment-center"><style>.blockspare-62f1cbbf-5319-4 .blockspare-block-testimonial-wrap{background-color:#ea4b50;border-width:null;border-style:null;border-color:#ececec;border-radius:null;padding:15px}.blockspare-62f1cbbf-5319-4 .blockspare-section-head-wrap{background-color:transparent;text-align:center;padding-top:5px;padding-bottom:5px;margin-top:5px;margin-bottom:5px}.blockspare-62f1cbbf-5319-4 .blockspare-section-head-wrap .blockspare-title{color:#ffffff;font-size:20px;font-family:Poppins;font-weight:400!important;padding-top:5px;padding-bottom:5px}.blockspare-62f1cbbf-5319-4 .blockspare-section-head-wrap .blockspare-subtitle{color:#ffffff;font-size:18px;font-family:Poppins;font-weight:Poppins!important;padding-top:5px;padding-bottom:5px}.blockspare-62f1cbbf-5319-4 .blockspare-description{color:#ffffff;font-size:16px;font-family:Default;text-align:center;font-weight:undefined!important}.blockspare-62f1cbbf-5319-4 .blockspare-title-dash{color:#8b249c}@media screen and (max-width:1025px){.blockspare-62f1cbbf-5319-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-62f1cbbf-5319-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-62f1cbbf-5319-4 .blockspare-description{font-size:undefinedpx}}@media screen and (max-width:768px){.blockspare-62f1cbbf-5319-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-62f1cbbf-5319-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-62f1cbbf-5319-4 .blockspare-description{font-size:undefinedpx}}</style><div class="blockspare-block-testimonial-wrap"><div class="blockspare-author-wrap"><div class="blockspare-img-wrapper"><!-- wp:image {"align":"center","id":87,"width":160,"height":160,"sizeSlug":"full","linkDestination":"none","className":"is-style-rounded"} -->
					<div class="wp-block-image is-style-rounded"><figure class="aligncenter size-full is-resized"><img src="https://blockspare.com/demo/default/app/wp-content/uploads/sites/5/2021/09/pexels-javon-swaby-2778211-edited.jpg" alt="" class="wp-image-87" width="160" height="160"/></figure></div>
					<!-- /wp:image --></div></div><div class="blockspare-author-designation"><div class="blockspare-section-header-wrapper blockspare-blocks aligncenter"><div class="blockspare-section-head-wrap blockspare-style1 blockspare-center"><div class="blockspare-title-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><h2 class="blockspare-title">"Gorgeous Design"</h2><span class="blockspare-title-dash blockspare-lower-dash"></span></div><div class="blockspare-subtitle-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><p class="blockspare-subtitle">John Doe</p><span class="blockspare-title-dash blockspare-lower-dash"></span></div></div></div></div><div class="blockspare-testimonial-content"><p class="blockspare-description">Molestiae incidunt consequatur quis ipsa autem nam sit enim magni. Voluptas tempore rem. Explicabo a quaerat sint autem dolore ducimus ut consequatur neque quaerat fuga rem nihil nostrum.<br></p></div></div></div>
					<!-- /wp:blockspare/testimonial-item -->
					
					<!-- wp:blockspare/testimonial-item {"uniqueClass":"blockspare-d2fdf8aa-94fc-4","headerTitle":"\u0022Gorgeous Design\u0022","titleFontSize":20,"headerSubTitle":"Jane Doe","headertitleColor":"#ffffff","headersubtitleColor":"#ffffff","titleFontFamily":"Poppins","titleFontWeight":"400","titleFontSubset":"latin","titleLoadGoogleFonts":true,"subTitleFontFamily":"Poppins","subTitleFontWeight":"400","subTitleFontSubset":"latin","subTitleLoadGoogleFonts":true,"testimonialDescription":"Molestiae incidunt consequatur quis ipsa autem nam sit enim magni. Voluptas tempore rem. Explicabo a quaerat sint autem dolore ducimus ut consequatur neque quaerat fuga rem nihil nostrum.\u003cbr\u003e","testimonialDescriptionTextColor":"#ffffff","backGroundColor":"#ea4b50","borderWidth":0} -->
					<div class="wp-block-blockspare-testimonial-item blockspare-d2fdf8aa-94fc-4 blockspare-testimonials textalignment-center"><style>.blockspare-d2fdf8aa-94fc-4 .blockspare-block-testimonial-wrap{background-color:#ea4b50;border-width:null;border-style:null;border-color:#ececec;border-radius:null;padding:15px}.blockspare-d2fdf8aa-94fc-4 .blockspare-section-head-wrap{background-color:transparent;text-align:center;padding-top:5px;padding-bottom:5px;margin-top:5px;margin-bottom:5px}.blockspare-d2fdf8aa-94fc-4 .blockspare-section-head-wrap .blockspare-title{color:#ffffff;font-size:20px;font-family:Poppins;font-weight:400!important;padding-top:5px;padding-bottom:5px}.blockspare-d2fdf8aa-94fc-4 .blockspare-section-head-wrap .blockspare-subtitle{color:#ffffff;font-size:18px;font-family:Poppins;font-weight:Poppins!important;padding-top:5px;padding-bottom:5px}.blockspare-d2fdf8aa-94fc-4 .blockspare-description{color:#ffffff;font-size:16px;font-family:Default;text-align:center;font-weight:undefined!important}.blockspare-d2fdf8aa-94fc-4 .blockspare-title-dash{color:#8b249c}@media screen and (max-width:1025px){.blockspare-d2fdf8aa-94fc-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-d2fdf8aa-94fc-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-d2fdf8aa-94fc-4 .blockspare-description{font-size:undefinedpx}}@media screen and (max-width:768px){.blockspare-d2fdf8aa-94fc-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-d2fdf8aa-94fc-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-d2fdf8aa-94fc-4 .blockspare-description{font-size:undefinedpx}}</style><div class="blockspare-block-testimonial-wrap"><div class="blockspare-author-wrap"><div class="blockspare-img-wrapper"><!-- wp:image {"align":"center","id":88,"width":160,"height":160,"sizeSlug":"full","linkDestination":"none","className":"is-style-rounded"} -->
					<div class="wp-block-image is-style-rounded"><figure class="aligncenter size-full is-resized"><img src="https://blockspare.com/demo/default/app/wp-content/uploads/sites/5/2021/09/pexels-marcio-bordin-1840608-edited.jpg" alt="" class="wp-image-88" width="160" height="160"/></figure></div>
					<!-- /wp:image --></div></div><div class="blockspare-author-designation"><div class="blockspare-section-header-wrapper blockspare-blocks aligncenter"><div class="blockspare-section-head-wrap blockspare-style1 blockspare-center"><div class="blockspare-title-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><h2 class="blockspare-title">"Gorgeous Design"</h2><span class="blockspare-title-dash blockspare-lower-dash"></span></div><div class="blockspare-subtitle-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><p class="blockspare-subtitle">Jane Doe</p><span class="blockspare-title-dash blockspare-lower-dash"></span></div></div></div></div><div class="blockspare-testimonial-content"><p class="blockspare-description">Molestiae incidunt consequatur quis ipsa autem nam sit enim magni. Voluptas tempore rem. Explicabo a quaerat sint autem dolore ducimus ut consequatur neque quaerat fuga rem nihil nostrum.<br></p></div></div></div>
					<!-- /wp:blockspare/testimonial-item --></div></div>
					<!-- /wp:blockspare/blockspare-testimonial -->',
					'category' => [ esc_html__( 'testimonial', 'blockspare' ) ],
					'keywords' => [
						esc_html__( 'testimonial', 'blockspare' ),
						
					],
					'image'    => BLOCKSPARE_BLOCK_LIBRARY_URL.'testimonials/testimonial-3.png',
				),
				array(
					'type'     => 'block',
					'key'      => 'bs_testimonial_4',
					'name'     => esc_html__( 'Testimonial 4', 'blockspare' ),
					'content'  => '<!-- wp:blockspare/blockspare-testimonial {"uniqueClass":"blockspare-fb01f576-39aa-4"} -->
					<div class="wp-block-blockspare-blockspare-testimonial alignwide blockspare-fb01f576-39aa-4 alignwide"><div class="blockspare-main-testimonial-wrapper blockspare-item blockspare-testimonial-columns-3 blockspare-testimonial-gap-1 bs-layout-1"><style>.blockspare-fb01f576-39aa-4 .blockspare-main-testimonial-wrapper{margin-top:30px;margin-bottom:30px}</style><!-- wp:blockspare/testimonial-item {"uniqueClass":"blockspare-227a926d-4582-4","headerTitle":" Kelly R. Davis ","titleFontSize":24,"headerSubTitle":" Instructor ","subtitlePaddingBottom":20,"titleFontFamily":"Helvetica","titleFontWeight":"700","titleFontSubset":"latin","subTitleFontFamily":"Helvetica","descriptionFontSize":0} -->
					<div class="wp-block-blockspare-testimonial-item blockspare-227a926d-4582-4 blockspare-testimonials textalignment-center"><style>.blockspare-227a926d-4582-4 .blockspare-block-testimonial-wrap{background-color:#fff;border-width:1px;border-style:solid;border-color:#ececec;border-radius:null;padding:15px}.blockspare-227a926d-4582-4 .blockspare-section-head-wrap{background-color:transparent;text-align:center;padding-top:5px;padding-bottom:5px;margin-top:5px;margin-bottom:5px}.blockspare-227a926d-4582-4 .blockspare-section-head-wrap .blockspare-title{color:#404040;font-size:24px;font-family:Helvetica;font-weight:700!important;padding-top:5px;padding-bottom:5px}.blockspare-227a926d-4582-4 .blockspare-section-head-wrap .blockspare-subtitle{color:#6d6d6d;font-size:18px;font-family:Helvetica;font-weight:Helvetica!important;padding-top:5px;padding-bottom:20px}.blockspare-227a926d-4582-4 .blockspare-description{color:#6d6d6d;font-size:0px;font-family:Default;text-align:center;font-weight:undefined!important}.blockspare-227a926d-4582-4 .blockspare-title-dash{color:#8b249c}@media screen and (max-width:1025px){.blockspare-227a926d-4582-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-227a926d-4582-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-227a926d-4582-4 .blockspare-description{font-size:undefinedpx}}@media screen and (max-width:768px){.blockspare-227a926d-4582-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-227a926d-4582-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-227a926d-4582-4 .blockspare-description{font-size:undefinedpx}}</style><div class="blockspare-block-testimonial-wrap"><div class="blockspare-author-wrap"><div class="blockspare-img-wrapper"><!-- wp:image {"align":"center","id":349,"sizeSlug":"full","linkDestination":"none"} -->
					<div class="wp-block-image"><figure class="aligncenter size-full"><img src="https://blockspare.com/demo/default/education/wp-content/uploads/sites/6/2021/09/1.jpg" alt="" class="wp-image-349"/></figure></div>
					<!-- /wp:image --></div></div><div class="blockspare-author-designation"><div class="blockspare-section-header-wrapper blockspare-blocks aligncenter"><div class="blockspare-section-head-wrap blockspare-style1 blockspare-center"><div class="blockspare-title-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><h2 class="blockspare-title"> Kelly R. Davis </h2><span class="blockspare-title-dash blockspare-lower-dash"></span></div><div class="blockspare-subtitle-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><p class="blockspare-subtitle"> Instructor </p><span class="blockspare-title-dash blockspare-lower-dash"></span></div></div></div></div><div class="blockspare-testimonial-content"><p class="blockspare-description">Donec odit magni, nesciunt pariatur! Nec, purus voluptate ridiculus odit nobis euismod, ac laudantium facere perferendis! </p></div></div></div>
					<!-- /wp:blockspare/testimonial-item -->
					
					<!-- wp:blockspare/testimonial-item {"uniqueClass":"blockspare-80997589-0e8c-4","headerTitle":" Kelly R. Davis ","titleFontSize":24,"headerSubTitle":" Instructor ","subtitlePaddingBottom":20,"titleFontFamily":"Helvetica","titleFontWeight":"700","titleFontSubset":"latin","subTitleFontFamily":"Helvetica","descriptionFontSize":0} -->
					<div class="wp-block-blockspare-testimonial-item blockspare-80997589-0e8c-4 blockspare-testimonials textalignment-center"><style>.blockspare-80997589-0e8c-4 .blockspare-block-testimonial-wrap{background-color:#fff;border-width:1px;border-style:solid;border-color:#ececec;border-radius:null;padding:15px}.blockspare-80997589-0e8c-4 .blockspare-section-head-wrap{background-color:transparent;text-align:center;padding-top:5px;padding-bottom:5px;margin-top:5px;margin-bottom:5px}.blockspare-80997589-0e8c-4 .blockspare-section-head-wrap .blockspare-title{color:#404040;font-size:24px;font-family:Helvetica;font-weight:700!important;padding-top:5px;padding-bottom:5px}.blockspare-80997589-0e8c-4 .blockspare-section-head-wrap .blockspare-subtitle{color:#6d6d6d;font-size:18px;font-family:Helvetica;font-weight:Helvetica!important;padding-top:5px;padding-bottom:20px}.blockspare-80997589-0e8c-4 .blockspare-description{color:#6d6d6d;font-size:0px;font-family:Default;text-align:center;font-weight:undefined!important}.blockspare-80997589-0e8c-4 .blockspare-title-dash{color:#8b249c}@media screen and (max-width:1025px){.blockspare-80997589-0e8c-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-80997589-0e8c-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-80997589-0e8c-4 .blockspare-description{font-size:undefinedpx}}@media screen and (max-width:768px){.blockspare-80997589-0e8c-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-80997589-0e8c-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-80997589-0e8c-4 .blockspare-description{font-size:undefinedpx}}</style><div class="blockspare-block-testimonial-wrap"><div class="blockspare-author-wrap"><div class="blockspare-img-wrapper"><!-- wp:image {"align":"center","id":356,"sizeSlug":"full","linkDestination":"none"} -->
					<div class="wp-block-image"><figure class="aligncenter size-full"><img src="https://blockspare.com/demo/default/education/wp-content/uploads/sites/6/2021/09/4-1.jpg" alt="" class="wp-image-356"/></figure></div>
					<!-- /wp:image --></div></div><div class="blockspare-author-designation"><div class="blockspare-section-header-wrapper blockspare-blocks aligncenter"><div class="blockspare-section-head-wrap blockspare-style1 blockspare-center"><div class="blockspare-title-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><h2 class="blockspare-title"> Kelly R. Davis </h2><span class="blockspare-title-dash blockspare-lower-dash"></span></div><div class="blockspare-subtitle-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><p class="blockspare-subtitle"> Instructor </p><span class="blockspare-title-dash blockspare-lower-dash"></span></div></div></div></div><div class="blockspare-testimonial-content"><p class="blockspare-description">Donec odit magni, nesciunt pariatur! Nec, purus voluptate ridiculus odit nobis euismod, ac laudantium facere perferendis! </p></div></div></div>
					<!-- /wp:blockspare/testimonial-item -->
					
					<!-- wp:blockspare/testimonial-item {"uniqueClass":"blockspare-901b478d-fe35-4","headerTitle":" Kelly R. Davis ","titleFontSize":24,"headerSubTitle":" Instructor ","subtitlePaddingBottom":20,"titleFontFamily":"Helvetica","titleFontWeight":"700","titleFontSubset":"latin","subTitleFontFamily":"Helvetica","descriptionFontSize":0} -->
					<div class="wp-block-blockspare-testimonial-item blockspare-901b478d-fe35-4 blockspare-testimonials textalignment-center"><style>.blockspare-901b478d-fe35-4 .blockspare-block-testimonial-wrap{background-color:#fff;border-width:1px;border-style:solid;border-color:#ececec;border-radius:null;padding:15px}.blockspare-901b478d-fe35-4 .blockspare-section-head-wrap{background-color:transparent;text-align:center;padding-top:5px;padding-bottom:5px;margin-top:5px;margin-bottom:5px}.blockspare-901b478d-fe35-4 .blockspare-section-head-wrap .blockspare-title{color:#404040;font-size:24px;font-family:Helvetica;font-weight:700!important;padding-top:5px;padding-bottom:5px}.blockspare-901b478d-fe35-4 .blockspare-section-head-wrap .blockspare-subtitle{color:#6d6d6d;font-size:18px;font-family:Helvetica;font-weight:Helvetica!important;padding-top:5px;padding-bottom:20px}.blockspare-901b478d-fe35-4 .blockspare-description{color:#6d6d6d;font-size:0px;font-family:Default;text-align:center;font-weight:undefined!important}.blockspare-901b478d-fe35-4 .blockspare-title-dash{color:#8b249c}@media screen and (max-width:1025px){.blockspare-901b478d-fe35-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-901b478d-fe35-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-901b478d-fe35-4 .blockspare-description{font-size:undefinedpx}}@media screen and (max-width:768px){.blockspare-901b478d-fe35-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-901b478d-fe35-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-901b478d-fe35-4 .blockspare-description{font-size:undefinedpx}}</style><div class="blockspare-block-testimonial-wrap"><div class="blockspare-author-wrap"><div class="blockspare-img-wrapper"><!-- wp:image {"align":"center","id":348,"sizeSlug":"full","linkDestination":"none"} -->
					<div class="wp-block-image"><figure class="aligncenter size-full"><img src="https://blockspare.com/demo/default/education/wp-content/uploads/sites/6/2021/09/2-1.jpg" alt="" class="wp-image-348"/></figure></div>
					<!-- /wp:image --></div></div><div class="blockspare-author-designation"><div class="blockspare-section-header-wrapper blockspare-blocks aligncenter"><div class="blockspare-section-head-wrap blockspare-style1 blockspare-center"><div class="blockspare-title-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><h2 class="blockspare-title"> Kelly R. Davis </h2><span class="blockspare-title-dash blockspare-lower-dash"></span></div><div class="blockspare-subtitle-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><p class="blockspare-subtitle"> Instructor </p><span class="blockspare-title-dash blockspare-lower-dash"></span></div></div></div></div><div class="blockspare-testimonial-content"><p class="blockspare-description">Donec odit magni, nesciunt pariatur! Nec, purus voluptate ridiculus odit nobis euismod, ac laudantium facere perferendis! </p></div></div></div>
					<!-- /wp:blockspare/testimonial-item --></div></div>
					<!-- /wp:blockspare/blockspare-testimonial -->',
					'category' => [ esc_html__( 'testimonial', 'blockspare' ) ],
					'keywords' => [
						esc_html__( 'testimonial', 'blockspare' ),
						
					],
					'image'    => BLOCKSPARE_BLOCK_LIBRARY_URL.'testimonials/testimonial-4.png',
				),
			array(
				'type'     => 'block',
				'key'      => 'bs_testimonial_5',
				'name'     => esc_html__( 'Testimonial 5', 'blockspare' ),
				'content'  => '<!-- wp:blockspare/blockspare-testimonial {"uniqueClass":"blockspare-37243f62-830c-4"} -->
				<div class="wp-block-blockspare-blockspare-testimonial alignwide blockspare-37243f62-830c-4 alignwide"><div class="blockspare-main-testimonial-wrapper blockspare-item blockspare-testimonial-columns-3 blockspare-testimonial-gap-1 bs-layout-1"><style>.blockspare-37243f62-830c-4 .blockspare-main-testimonial-wrapper{margin-top:30px;margin-bottom:30px}</style><!-- wp:blockspare/testimonial-item {"uniqueClass":"blockspare-1f6acaa2-46d9-4","sectionAlignment":"left","headerTitle":"Apartments","titleFontSize":24,"headerSubTitle":"34,900 / Month","headertitleColor":"#384260","headersubtitleColor":"#fcb332","headerlayoutOption":"blockspare-style3","titleFontFamily":"Helvetica","titleFontWeight":"600","subTitleFontSize":24,"subTitleFontFamily":"Helvetica","subTitleFontWeight":"400","testimonialDescriptionTextColor":"#aaaaaa","descriptionFontFamily":"Helvetica"} -->
				<div class="wp-block-blockspare-testimonial-item blockspare-1f6acaa2-46d9-4 blockspare-testimonials textalignment-left"><style>.blockspare-1f6acaa2-46d9-4 .blockspare-block-testimonial-wrap{background-color:#fff;border-width:1px;border-style:solid;border-color:#ececec;border-radius:null;padding:15px}.blockspare-1f6acaa2-46d9-4 .blockspare-section-head-wrap{background-color:transparent;text-align:left;padding-top:5px;padding-bottom:5px;margin-top:5px;margin-bottom:5px}.blockspare-1f6acaa2-46d9-4 .blockspare-section-head-wrap .blockspare-title{color:#384260;font-size:24px;font-family:Helvetica;font-weight:600!important;padding-top:5px;padding-bottom:5px}.blockspare-1f6acaa2-46d9-4 .blockspare-section-head-wrap .blockspare-subtitle{color:#fcb332;font-size:24px;font-family:Helvetica;font-weight:Helvetica!important;padding-top:5px;padding-bottom:5px}.blockspare-1f6acaa2-46d9-4 .blockspare-description{color:#aaaaaa;font-size:16px;font-family:Helvetica;text-align:left;font-weight:undefined!important}.blockspare-1f6acaa2-46d9-4 .blockspare-title-dash{color:#8b249c}@media screen and (max-width:1025px){.blockspare-1f6acaa2-46d9-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-1f6acaa2-46d9-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-1f6acaa2-46d9-4 .blockspare-description{font-size:undefinedpx}}@media screen and (max-width:768px){.blockspare-1f6acaa2-46d9-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-1f6acaa2-46d9-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-1f6acaa2-46d9-4 .blockspare-description{font-size:undefinedpx}}</style><div class="blockspare-block-testimonial-wrap"><div class="blockspare-author-wrap"><div class="blockspare-img-wrapper"><!-- wp:image {"align":"center","id":110,"sizeSlug":"full","linkDestination":"none"} -->
				<div class="wp-block-image"><figure class="aligncenter size-full"><img src="https://blockspare.com/demo/default/real-estate/wp-content/uploads/sites/8/2021/09/1-1.jpg" alt="" class="wp-image-110"/></figure></div>
				<!-- /wp:image --></div></div><div class="blockspare-author-designation"><div class="blockspare-section-header-wrapper blockspare-blocks aligncenter"><div class="blockspare-section-head-wrap blockspare-style3 blockspare-left"><div class="blockspare-title-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><h2 class="blockspare-title">Apartments</h2><span class="blockspare-title-dash blockspare-lower-dash"></span></div><div class="blockspare-subtitle-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><p class="blockspare-subtitle">34,900 / Month</p><span class="blockspare-title-dash blockspare-lower-dash"></span></div></div></div></div><div class="blockspare-testimonial-content"><p class="blockspare-description">Donec odit magni, nesciunt pariatur! Nec, purus voluptate ridiculus odit nobis euismod, ac laudantium facere perferendis! </p></div></div></div>
				<!-- /wp:blockspare/testimonial-item -->
				
				<!-- wp:blockspare/testimonial-item {"uniqueClass":"blockspare-cd6c2992-48c7-4","sectionAlignment":"left","headerTitle":"Houses","titleFontSize":24,"headerSubTitle":"56,900 / Month","headertitleColor":"#384260","headersubtitleColor":"#fcb332","headerlayoutOption":"blockspare-style3","titleFontFamily":"Helvetica","titleFontWeight":"600","subTitleFontSize":24,"subTitleFontFamily":"Helvetica","subTitleFontWeight":"400","testimonialDescriptionTextColor":"#cccccc","descriptionFontFamily":"Helvetica","descriptionFontWeight":"default"} -->
				<div class="wp-block-blockspare-testimonial-item blockspare-cd6c2992-48c7-4 blockspare-testimonials textalignment-left"><style>.blockspare-cd6c2992-48c7-4 .blockspare-block-testimonial-wrap{background-color:#fff;border-width:1px;border-style:solid;border-color:#ececec;border-radius:null;padding:15px}.blockspare-cd6c2992-48c7-4 .blockspare-section-head-wrap{background-color:transparent;text-align:left;padding-top:5px;padding-bottom:5px;margin-top:5px;margin-bottom:5px}.blockspare-cd6c2992-48c7-4 .blockspare-section-head-wrap .blockspare-title{color:#384260;font-size:24px;font-family:Helvetica;font-weight:600!important;padding-top:5px;padding-bottom:5px}.blockspare-cd6c2992-48c7-4 .blockspare-section-head-wrap .blockspare-subtitle{color:#fcb332;font-size:24px;font-family:Helvetica;font-weight:Helvetica!important;padding-top:5px;padding-bottom:5px}.blockspare-cd6c2992-48c7-4 .blockspare-description{color:#cccccc;font-size:16px;font-family:Helvetica;text-align:left;font-weight:default!important}.blockspare-cd6c2992-48c7-4 .blockspare-title-dash{color:#8b249c}@media screen and (max-width:1025px){.blockspare-cd6c2992-48c7-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-cd6c2992-48c7-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-cd6c2992-48c7-4 .blockspare-description{font-size:undefinedpx}}@media screen and (max-width:768px){.blockspare-cd6c2992-48c7-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-cd6c2992-48c7-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-cd6c2992-48c7-4 .blockspare-description{font-size:undefinedpx}}</style><div class="blockspare-block-testimonial-wrap"><div class="blockspare-author-wrap"><div class="blockspare-img-wrapper"><!-- wp:image {"align":"center","id":111,"sizeSlug":"full","linkDestination":"none"} -->
				<div class="wp-block-image"><figure class="aligncenter size-full"><img src="https://blockspare.com/demo/default/real-estate/wp-content/uploads/sites/8/2021/09/2-4.jpg" alt="" class="wp-image-111"/></figure></div>
				<!-- /wp:image --></div></div><div class="blockspare-author-designation"><div class="blockspare-section-header-wrapper blockspare-blocks aligncenter"><div class="blockspare-section-head-wrap blockspare-style3 blockspare-left"><div class="blockspare-title-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><h2 class="blockspare-title">Houses</h2><span class="blockspare-title-dash blockspare-lower-dash"></span></div><div class="blockspare-subtitle-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><p class="blockspare-subtitle">56,900 / Month</p><span class="blockspare-title-dash blockspare-lower-dash"></span></div></div></div></div><div class="blockspare-testimonial-content"><p class="blockspare-description">Donec odit magni, nesciunt pariatur! Nec, purus voluptate ridiculus odit nobis euismod, ac laudantium facere perferendis! </p></div></div></div>
				<!-- /wp:blockspare/testimonial-item -->
				
				<!-- wp:blockspare/testimonial-item {"uniqueClass":"blockspare-3dfe5b7d-e6ba-4","sectionAlignment":"left","headerTitle":"Offices","titleFontSize":24,"headerSubTitle":"44,900 / Month","headertitleColor":"#384260","headersubtitleColor":"#fcb332","headerlayoutOption":"blockspare-style3","titleFontFamily":"Helvetica","titleFontWeight":"600","subTitleFontSize":24,"subTitleFontFamily":"Helvetica","subTitleFontWeight":"400","testimonialDescriptionTextColor":"#cccccc","descriptionFontFamily":"Helvetica"} -->
				<div class="wp-block-blockspare-testimonial-item blockspare-3dfe5b7d-e6ba-4 blockspare-testimonials textalignment-left"><style>.blockspare-3dfe5b7d-e6ba-4 .blockspare-block-testimonial-wrap{background-color:#fff;border-width:1px;border-style:solid;border-color:#ececec;border-radius:null;padding:15px}.blockspare-3dfe5b7d-e6ba-4 .blockspare-section-head-wrap{background-color:transparent;text-align:left;padding-top:5px;padding-bottom:5px;margin-top:5px;margin-bottom:5px}.blockspare-3dfe5b7d-e6ba-4 .blockspare-section-head-wrap .blockspare-title{color:#384260;font-size:24px;font-family:Helvetica;font-weight:600!important;padding-top:5px;padding-bottom:5px}.blockspare-3dfe5b7d-e6ba-4 .blockspare-section-head-wrap .blockspare-subtitle{color:#fcb332;font-size:24px;font-family:Helvetica;font-weight:Helvetica!important;padding-top:5px;padding-bottom:5px}.blockspare-3dfe5b7d-e6ba-4 .blockspare-description{color:#cccccc;font-size:16px;font-family:Helvetica;text-align:left;font-weight:undefined!important}.blockspare-3dfe5b7d-e6ba-4 .blockspare-title-dash{color:#8b249c}@media screen and (max-width:1025px){.blockspare-3dfe5b7d-e6ba-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-3dfe5b7d-e6ba-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-3dfe5b7d-e6ba-4 .blockspare-description{font-size:undefinedpx}}@media screen and (max-width:768px){.blockspare-3dfe5b7d-e6ba-4 .blockspare-section-head-wrap .blockspare-title{font-size:undefinedpx}.blockspare-3dfe5b7d-e6ba-4 .blockspare-section-head-wrap .blockspare-subtitle{font-size:undefinedpx}.blockspare-3dfe5b7d-e6ba-4 .blockspare-description{font-size:undefinedpx}}</style><div class="blockspare-block-testimonial-wrap"><div class="blockspare-author-wrap"><div class="blockspare-img-wrapper"><!-- wp:image {"align":"center","id":110,"sizeSlug":"full","linkDestination":"none"} -->
				<div class="wp-block-image"><figure class="aligncenter size-full"><img src="https://blockspare.com/demo/default/real-estate/wp-content/uploads/sites/8/2021/09/1-1.jpg" alt="" class="wp-image-110"/></figure></div>
				<!-- /wp:image --></div></div><div class="blockspare-author-designation"><div class="blockspare-section-header-wrapper blockspare-blocks aligncenter"><div class="blockspare-section-head-wrap blockspare-style3 blockspare-left"><div class="blockspare-title-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><h2 class="blockspare-title">Offices</h2><span class="blockspare-title-dash blockspare-lower-dash"></span></div><div class="blockspare-subtitle-wrapper"><span class="blockspare-title-dash blockspare-upper-dash"></span><p class="blockspare-subtitle">44,900 / Month</p><span class="blockspare-title-dash blockspare-lower-dash"></span></div></div></div></div><div class="blockspare-testimonial-content"><p class="blockspare-description">Donec odit magni, nesciunt pariatur! Nec, purus voluptate ridiculus odit nobis euismod, ac laudantium facere perferendis! </p></div></div></div>
				<!-- /wp:blockspare/testimonial-item --></div></div>
				<!-- /wp:blockspare/blockspare-testimonial -->',
				'category' => [ esc_html__( 'testimonial', 'blockspare' ) ],
				'keywords' => [
					esc_html__( 'testimonial', 'blockspare' ),
					
				],
				'image'    => BLOCKSPARE_BLOCK_LIBRARY_URL.'testimonials/testimonial-5.png',
		)
                
				);

            return array_merge_recursive( $blocks_lists, $block_library_list );
        }
	}
}
Blockspare_Testimonials_Template_Block::get_instance()->run();