<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! class_exists( 'Blockspare_Price_Table_Template_Block' ) ) {

	class Blockspare_Price_Table_Template_Block extends Blockspare_Import_Block_Base{
		public static function get_instance() {

			static $instance = null;
			if ( null === $instance ) {
				$instance = new self();
			}
			return $instance;

		}
        public function add_block_template_library( $blocks_lists ){

            $block_library_list = array(
					array(
						'type'     => 'block',
						'key'      => 'bs_price_list_1',
						'name'     => esc_html__( 'Price List 1', 'blockspare' ),
						'content'  => '<!-- wp:blockspare/blockspare-price-list {"align":"wide","uniqueId":"4a7f18","marginTop":0,"marginBottom":0} -->
                        <div class="blockspare-block-pricelist blockspare-blocks blockspare-block-4a7f18 alignwide wp-block-blockspare-blockspare-price-list alignwide blockspare-4a7f183f-c845-4"><div class="blockspare-pricelist-wrapper"><style>.blockspare-4a7f183f-c845-4 .blockspare-pricelist-wrapper{background-color:#fff}</style><!-- wp:blockspare/list-item {"uniqueClass":"blockspare-dadb1ad5-2ec3-4","priceTitle":"Baby Back Ribs","priceDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. \u003cbr\u003eUt elit tellus, luctus nec ullamcorper.","priceUnitColor":"#ffffff","titleFontFamily":"Roboto Condensed","titleFontWeight":"700","titleFontSubset":"latin","titleLoadGoogleFonts":true,"priceUnitFontFamily":"Roboto Condensed","priceUnitFontWeight":"700","priceUnitFontSubset":"latin","priceUnitLoadGoogleFonts":true,"descriptionFontFamily":"Roboto Condensed","descriptionFontWeight":"default","descriptionFontSubset":"latin","descriptionLoadGoogleFonts":true} -->
                        <div class="wp-block-blockspare-list-item blockspare-dadb1ad5-2ec3-4 blockspare-pircelist"><style>.blockspare-dadb1ad5-2ec3-4 .blockspare-price-list-wrap{text-align:left;padding-top:20px;padding-right:20px;padding-bottom:20px;padding-left:20px;margin-top:30px;margin-right:0px;margin-bottom:30px;margin-left:0px;background-color:#fff;border-radius:null}.blockspare-dadb1ad5-2ec3-4 .blockspare-price-list-wrap .blockspare-block-icon{background-color:#8b249c;border-color:#8b249c;color:#fff;border-radius:50%}.blockspare-dadb1ad5-2ec3-4 .blockspare-price-divider{color:#6d6d6d}.blockspare-dadb1ad5-2ec3-4 .blockspare-title{color:#404040;font-size:18px!important;font-family:Roboto Condensed!important;font-weight:700!important}.blockspare-dadb1ad5-2ec3-4 .blockspare-price{color:#3c1a5b;font-size:18px!important;font-family:Roboto Condensed!important;font-weight:700!important}.blockspare-dadb1ad5-2ec3-4 .blockspare-unit{color:#ffffff;font-size:13px;font-family:Roboto Condensed;font-weight:700}.blockspare-dadb1ad5-2ec3-4 .blockspare-description{color:#6d6d6d;font-size:18px!important;font-family:Roboto Condensed!important;font-weight:default!important}@media screen and (max-width:1025px){.blockspare-dadb1ad5-2ec3-4 .blockspare-title{font-size:undefinedpx!important}.blockspare-dadb1ad5-2ec3-4 .blockspare-price,.blockspare-dadb1ad5-2ec3-4{font-size:undefinedpx!important}.blockspare-dadb1ad5-2ec3-4 .blockspare-unit{font-size:NaNpx!important}.blockspare-dadb1ad5-2ec3-4 .blockspare-description{font-size:undefinedpx!important}}@media screen and (max-width:768px){.blockspare-dadb1ad5-2ec3-4 .blockspare-title{font-size:undefinedpx!important}.blockspare-dadb1ad5-2ec3-4 .blockspare-price{font-size:undefinedpx!important}.blockspare-dadb1ad5-2ec3-4 .blockspare-unit{font-size:NaNpx!important}.blockspare-dadb1ad5-2ec3-4 .blockspare-description{font-size:undefinedpx!important}}</style><div class="blockspare-price-list-wrap blockspare-layout1 blockspare-before-price"><div class="blockspare-imge-wrapper"><!-- wp:image {"align":"center","id":202,"sizeSlug":"full","linkDestination":"none","className":"is-style-rounded"} -->
                        <div class="wp-block-image is-style-rounded"><figure class="aligncenter size-full"><img src="https://blockspare.com/demo/default/restaurant/wp-content/uploads/sites/4/2021/09/potato.png" alt="" class="wp-image-202"/></figure></div>
                        <!-- /wp:image --></div><div class="blockspare-price-content"><div class="blockspare-price-header"><h4 class="blockspare-title">Baby Back Ribs</h4><span class="blockspare-price-divider"></span><div class="blockspare-price-unit-wrap"><span class="blockspare-price">100</span><span class="blockspare-unit">$</span></div></div><p class="blockspare-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. <br>Ut elit tellus, luctus nec ullamcorper.</p></div></div></div>
                        <!-- /wp:blockspare/list-item -->
                        
                        <!-- wp:blockspare/list-item {"uniqueClass":"blockspare-1e8588dc-4bea-4","priceTitle":"Baby Back Ribs","priceDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. \u003cbr\u003eUt elit tellus, luctus nec ullamcorper.","priceUnitColor":"#ffffff","titleFontFamily":"Roboto Condensed","titleFontWeight":"700","titleFontSubset":"latin","titleLoadGoogleFonts":true,"priceUnitFontFamily":"Roboto Condensed","priceUnitFontWeight":"700","priceUnitFontSubset":"latin","priceUnitLoadGoogleFonts":true,"descriptionFontFamily":"Roboto Condensed","descriptionFontWeight":"default","descriptionFontSubset":"latin","descriptionLoadGoogleFonts":true} -->
                        <div class="wp-block-blockspare-list-item blockspare-1e8588dc-4bea-4 blockspare-pircelist"><style>.blockspare-1e8588dc-4bea-4 .blockspare-price-list-wrap{text-align:left;padding-top:20px;padding-right:20px;padding-bottom:20px;padding-left:20px;margin-top:30px;margin-right:0px;margin-bottom:30px;margin-left:0px;background-color:#fff;border-radius:null}.blockspare-1e8588dc-4bea-4 .blockspare-price-list-wrap .blockspare-block-icon{background-color:#8b249c;border-color:#8b249c;color:#fff;border-radius:50%}.blockspare-1e8588dc-4bea-4 .blockspare-price-divider{color:#6d6d6d}.blockspare-1e8588dc-4bea-4 .blockspare-title{color:#404040;font-size:18px!important;font-family:Roboto Condensed!important;font-weight:700!important}.blockspare-1e8588dc-4bea-4 .blockspare-price{color:#3c1a5b;font-size:18px!important;font-family:Roboto Condensed!important;font-weight:700!important}.blockspare-1e8588dc-4bea-4 .blockspare-unit{color:#ffffff;font-size:13px;font-family:Roboto Condensed;font-weight:700}.blockspare-1e8588dc-4bea-4 .blockspare-description{color:#6d6d6d;font-size:18px!important;font-family:Roboto Condensed!important;font-weight:default!important}@media screen and (max-width:1025px){.blockspare-1e8588dc-4bea-4 .blockspare-title{font-size:undefinedpx!important}.blockspare-1e8588dc-4bea-4 .blockspare-price,.blockspare-1e8588dc-4bea-4{font-size:undefinedpx!important}.blockspare-1e8588dc-4bea-4 .blockspare-unit{font-size:NaNpx!important}.blockspare-1e8588dc-4bea-4 .blockspare-description{font-size:undefinedpx!important}}@media screen and (max-width:768px){.blockspare-1e8588dc-4bea-4 .blockspare-title{font-size:undefinedpx!important}.blockspare-1e8588dc-4bea-4 .blockspare-price{font-size:undefinedpx!important}.blockspare-1e8588dc-4bea-4 .blockspare-unit{font-size:NaNpx!important}.blockspare-1e8588dc-4bea-4 .blockspare-description{font-size:undefinedpx!important}}</style><div class="blockspare-price-list-wrap blockspare-layout1 blockspare-before-price"><div class="blockspare-imge-wrapper"><!-- wp:image {"align":"center","id":202,"sizeSlug":"full","linkDestination":"none","className":"is-style-rounded"} -->
                        <div class="wp-block-image is-style-rounded"><figure class="aligncenter size-full"><img src="https://blockspare.com/demo/default/restaurant/wp-content/uploads/sites/4/2021/09/potato.png" alt="" class="wp-image-202"/></figure></div>
                        <!-- /wp:image --></div><div class="blockspare-price-content"><div class="blockspare-price-header"><h4 class="blockspare-title">Baby Back Ribs</h4><span class="blockspare-price-divider"></span><div class="blockspare-price-unit-wrap"><span class="blockspare-price">100</span><span class="blockspare-unit">$</span></div></div><p class="blockspare-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. <br>Ut elit tellus, luctus nec ullamcorper.</p></div></div></div>
                        <!-- /wp:blockspare/list-item -->
                        
                        <!-- wp:blockspare/list-item {"uniqueClass":"blockspare-9c97dc8e-184a-4","priceTitle":"Baby Back Ribs","priceDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. \u003cbr\u003eUt elit tellus, luctus nec ullamcorper.","priceUnitColor":"#ffffff","titleFontFamily":"Roboto Condensed","titleFontWeight":"700","titleFontSubset":"latin","titleLoadGoogleFonts":true,"priceUnitFontFamily":"Roboto Condensed","priceUnitFontWeight":"700","priceUnitFontSubset":"latin","priceUnitLoadGoogleFonts":true,"descriptionFontFamily":"Roboto Condensed","descriptionFontWeight":"default","descriptionFontSubset":"latin","descriptionLoadGoogleFonts":true} -->
                        <div class="wp-block-blockspare-list-item blockspare-9c97dc8e-184a-4 blockspare-pircelist"><style>.blockspare-9c97dc8e-184a-4 .blockspare-price-list-wrap{text-align:left;padding-top:20px;padding-right:20px;padding-bottom:20px;padding-left:20px;margin-top:30px;margin-right:0px;margin-bottom:30px;margin-left:0px;background-color:#fff;border-radius:null}.blockspare-9c97dc8e-184a-4 .blockspare-price-list-wrap .blockspare-block-icon{background-color:#8b249c;border-color:#8b249c;color:#fff;border-radius:50%}.blockspare-9c97dc8e-184a-4 .blockspare-price-divider{color:#6d6d6d}.blockspare-9c97dc8e-184a-4 .blockspare-title{color:#404040;font-size:18px!important;font-family:Roboto Condensed!important;font-weight:700!important}.blockspare-9c97dc8e-184a-4 .blockspare-price{color:#3c1a5b;font-size:18px!important;font-family:Roboto Condensed!important;font-weight:700!important}.blockspare-9c97dc8e-184a-4 .blockspare-unit{color:#ffffff;font-size:13px;font-family:Roboto Condensed;font-weight:700}.blockspare-9c97dc8e-184a-4 .blockspare-description{color:#6d6d6d;font-size:18px!important;font-family:Roboto Condensed!important;font-weight:default!important}@media screen and (max-width:1025px){.blockspare-9c97dc8e-184a-4 .blockspare-title{font-size:undefinedpx!important}.blockspare-9c97dc8e-184a-4 .blockspare-price,.blockspare-9c97dc8e-184a-4{font-size:undefinedpx!important}.blockspare-9c97dc8e-184a-4 .blockspare-unit{font-size:NaNpx!important}.blockspare-9c97dc8e-184a-4 .blockspare-description{font-size:undefinedpx!important}}@media screen and (max-width:768px){.blockspare-9c97dc8e-184a-4 .blockspare-title{font-size:undefinedpx!important}.blockspare-9c97dc8e-184a-4 .blockspare-price{font-size:undefinedpx!important}.blockspare-9c97dc8e-184a-4 .blockspare-unit{font-size:NaNpx!important}.blockspare-9c97dc8e-184a-4 .blockspare-description{font-size:undefinedpx!important}}</style><div class="blockspare-price-list-wrap blockspare-layout1 blockspare-before-price"><div class="blockspare-imge-wrapper"><!-- wp:image {"align":"center","id":202,"sizeSlug":"full","linkDestination":"none","className":"is-style-rounded"} -->
                        <div class="wp-block-image is-style-rounded"><figure class="aligncenter size-full"><img src="https://blockspare.com/demo/default/restaurant/wp-content/uploads/sites/4/2021/09/potato.png" alt="" class="wp-image-202"/></figure></div>
                        <!-- /wp:image --></div><div class="blockspare-price-content"><div class="blockspare-price-header"><h4 class="blockspare-title">Baby Back Ribs</h4><span class="blockspare-price-divider"></span><div class="blockspare-price-unit-wrap"><span class="blockspare-price">100</span><span class="blockspare-unit">$</span></div></div><p class="blockspare-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. <br>Ut elit tellus, luctus nec ullamcorper.</p></div></div></div>
                        <!-- /wp:blockspare/list-item --></div></div>
                        <!-- /wp:blockspare/blockspare-price-list -->',
						'category' => [ esc_html__( 'price list', 'blockspare' ) ],
						'keywords' => [
							esc_html__( 'price list', 'blockspare' ),
							
						],
						'image'    => BLOCKSPARE_BLOCK_LIBRARY_URL.'price-list/price-list-1.png',
						
                    ),
                    array(
						'type'     => 'block',
						'key'      => 'bs_price_list_2',
						'name'     => esc_html__( 'Price List 2', 'blockspare' ),
						'content'  => '<!-- wp:blockspare/blockspare-price-list {"uniqueId":"eda2c9","className":"blockspare-e4d39b89-4c47-4 blockspare-fbe7ab90-5dd6-4"} -->
                        <div class="blockspare-block-pricelist blockspare-blocks blockspare-block-eda2c9 alignundefined wp-block-blockspare-blockspare-price-list blockspare-e4d39b89-4c47-4 blockspare-fbe7ab90-5dd6-4 blockspare-eda2c98a-41b8-4"><div class="blockspare-pricelist-wrapper"><style>.blockspare-eda2c98a-41b8-4 .blockspare-pricelist-wrapper{margin-top:30px;margin-bottom:30px;background-color:#fff}</style><!-- wp:blockspare/list-item {"uniqueClass":"blockspare-7854a800-2e0e-4","priceTitle":"Chilli Chicken","priceDescription":"Lorem ipsum dolor sit amet, feugiat delicata.","price":"40","showImage":false,"titleFontFamily":"Helvetica","titleFontWeight":"700","priceUnitFontSize":32,"priceUnitFontFamily":"Helvetica","priceUnitFontWeight":"700","descriptionFontFamily":"Helvetica","paddingTop":0,"paddingRight":0,"paddingLeft":0} -->
                        <div class="wp-block-blockspare-list-item blockspare-7854a800-2e0e-4 blockspare-pircelist"><style>.blockspare-7854a800-2e0e-4 .blockspare-price-list-wrap{text-align:left;padding-top:0px;padding-right:0px;padding-bottom:20px;padding-left:0px;margin-top:30px;margin-right:0px;margin-bottom:30px;margin-left:0px;background-color:#fff;border-radius:null}.blockspare-7854a800-2e0e-4 .blockspare-price-list-wrap .blockspare-block-icon{background-color:#8b249c;border-color:#8b249c;color:#fff;border-radius:50%}.blockspare-7854a800-2e0e-4 .blockspare-price-divider{color:#6d6d6d}.blockspare-7854a800-2e0e-4 .blockspare-title{color:#404040;font-size:18px!important;font-family:Helvetica!important;font-weight:700!important}.blockspare-7854a800-2e0e-4 .blockspare-price{color:#3c1a5b;font-size:32px!important;font-family:Helvetica!important;font-weight:700!important}.blockspare-7854a800-2e0e-4 .blockspare-unit{color:#3c1a5b;font-size:24px;font-family:Helvetica;font-weight:700}.blockspare-7854a800-2e0e-4 .blockspare-description{color:#6d6d6d;font-size:18px!important;font-family:Helvetica!important;font-weight:undefined!important}@media screen and (max-width:1025px){.blockspare-7854a800-2e0e-4 .blockspare-title{font-size:undefinedpx!important}.blockspare-7854a800-2e0e-4 .blockspare-price,.blockspare-7854a800-2e0e-4{font-size:undefinedpx!important}.blockspare-7854a800-2e0e-4 .blockspare-unit{font-size:NaNpx!important}.blockspare-7854a800-2e0e-4 .blockspare-description{font-size:undefinedpx!important}}@media screen and (max-width:768px){.blockspare-7854a800-2e0e-4 .blockspare-title{font-size:undefinedpx!important}.blockspare-7854a800-2e0e-4 .blockspare-price{font-size:undefinedpx!important}.blockspare-7854a800-2e0e-4 .blockspare-unit{font-size:NaNpx!important}.blockspare-7854a800-2e0e-4 .blockspare-description{font-size:undefinedpx!important}}</style><div class="blockspare-price-list-wrap blockspare-layout1 blockspare-before-price"><div class="blockspare-imge-wrapper"></div><div class="blockspare-price-content"><div class="blockspare-price-header"><h4 class="blockspare-title">Chilli Chicken</h4><span class="blockspare-price-divider"></span><div class="blockspare-price-unit-wrap"><span class="blockspare-price">40</span><span class="blockspare-unit">$</span></div></div><p class="blockspare-description">Lorem ipsum dolor sit amet, feugiat delicata.</p></div></div></div>
                        <!-- /wp:blockspare/list-item -->
                        
                        <!-- wp:blockspare/list-item {"uniqueClass":"blockspare-0b9bd3dd-2196-4","priceTitle":" Paneer Tikkas ","priceDescription":"Lorem ipsum dolor sit amet, feugiat delicata.","price":"40","showImage":false,"titleFontFamily":"Helvetica","titleFontWeight":"700","priceUnitFontSize":32,"priceUnitFontFamily":"Helvetica","priceUnitFontWeight":"700","descriptionFontFamily":"Helvetica","paddingTop":0,"paddingRight":0,"paddingLeft":0} -->
                        <div class="wp-block-blockspare-list-item blockspare-0b9bd3dd-2196-4 blockspare-pircelist"><style>.blockspare-0b9bd3dd-2196-4 .blockspare-price-list-wrap{text-align:left;padding-top:0px;padding-right:0px;padding-bottom:20px;padding-left:0px;margin-top:30px;margin-right:0px;margin-bottom:30px;margin-left:0px;background-color:#fff;border-radius:null}.blockspare-0b9bd3dd-2196-4 .blockspare-price-list-wrap .blockspare-block-icon{background-color:#8b249c;border-color:#8b249c;color:#fff;border-radius:50%}.blockspare-0b9bd3dd-2196-4 .blockspare-price-divider{color:#6d6d6d}.blockspare-0b9bd3dd-2196-4 .blockspare-title{color:#404040;font-size:18px!important;font-family:Helvetica!important;font-weight:700!important}.blockspare-0b9bd3dd-2196-4 .blockspare-price{color:#3c1a5b;font-size:32px!important;font-family:Helvetica!important;font-weight:700!important}.blockspare-0b9bd3dd-2196-4 .blockspare-unit{color:#3c1a5b;font-size:24px;font-family:Helvetica;font-weight:700}.blockspare-0b9bd3dd-2196-4 .blockspare-description{color:#6d6d6d;font-size:18px!important;font-family:Helvetica!important;font-weight:undefined!important}@media screen and (max-width:1025px){.blockspare-0b9bd3dd-2196-4 .blockspare-title{font-size:undefinedpx!important}.blockspare-0b9bd3dd-2196-4 .blockspare-price,.blockspare-0b9bd3dd-2196-4{font-size:undefinedpx!important}.blockspare-0b9bd3dd-2196-4 .blockspare-unit{font-size:NaNpx!important}.blockspare-0b9bd3dd-2196-4 .blockspare-description{font-size:undefinedpx!important}}@media screen and (max-width:768px){.blockspare-0b9bd3dd-2196-4 .blockspare-title{font-size:undefinedpx!important}.blockspare-0b9bd3dd-2196-4 .blockspare-price{font-size:undefinedpx!important}.blockspare-0b9bd3dd-2196-4 .blockspare-unit{font-size:NaNpx!important}.blockspare-0b9bd3dd-2196-4 .blockspare-description{font-size:undefinedpx!important}}</style><div class="blockspare-price-list-wrap blockspare-layout1 blockspare-before-price"><div class="blockspare-imge-wrapper"></div><div class="blockspare-price-content"><div class="blockspare-price-header"><h4 class="blockspare-title"> Paneer Tikkas </h4><span class="blockspare-price-divider"></span><div class="blockspare-price-unit-wrap"><span class="blockspare-price">40</span><span class="blockspare-unit">$</span></div></div><p class="blockspare-description">Lorem ipsum dolor sit amet, feugiat delicata.</p></div></div></div>
                        <!-- /wp:blockspare/list-item --></div></div>
                        <!-- /wp:blockspare/blockspare-price-list -->',
						'category' => [ esc_html__( 'price list', 'blockspare' ) ],
						'keywords' => [
							esc_html__( 'price list', 'blockspare' ),
							
						],
						'image'    => BLOCKSPARE_BLOCK_LIBRARY_URL.'price-list/price-list-2.png',
						
                    )
				);

            return array_merge_recursive( $blocks_lists, $block_library_list );
        }
	}
}
Blockspare_Price_Table_Template_Block::get_instance()->run();